version: '2'
services:
  plex:
    container_name: plex
    image: plexinc/pms-docker
    restart: unless-stopped
    ports:
      - 32401:32400
    environment:
      - TZ=America/New_York
      - ADVERTISE_IP=https://mydomain.com:32397,http://mydomain.com:32397,http://192.168.1.148:32397/
    hostname: mydomain.com
    volumes:
      - /var/lib/plexmediaserver:/config
      - /var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Cache:/transcode
      - /srv/media:/data:ro
